### ISSUE TITLE
Ideas for deployment

### ISSUE THREAD

**Issue by miguelgfierro** [dsanmart/everywhere-reco#6]
Some ideas for the deployment of the ML models. 

You can do something simple with cherrypy, like https://github.com/miguelgfierro/sciblog_support/blob/main/Intro_to_Machine_Learning_API/Intro_to_Cloud_ML_with_Flask_and_CNTK.ipynb

Something more advanced would involve Kubernetes, like in this notebook: https://github.com/microsoft/recommenders/blob/main/examples/05_operationalize/als_movie_o16n.ipynb

**Comment by dsanmart** [comment]
Started exploring the Kubernetes solution for the deployment and created a new branch (cloud_features) for this issue.

**Comment by dsanmart** [comment]
Successfully created IaC for data bricks in Azure and linked Github repo for scheduling jobs with @pabloortegaa, @rayanmazari90 and @yahyalrq .

Next steps to take:
- [x] Migration of [load_data.py](https://github.com/dsanmart/everywhere-reco/blob/main/everywhere/datasets/load_data.py) from Google Drive API to Azure Blob Storage.
- [x] Create environment variables for the keys in Azure and include them in data bricks jobs.
- [x] Learn how to import the repo as a package in data bricks notebooks (ideally through the repo instead of a wheel file).
- [x] Design a good workflow with [Delta Live Tables](https://learn.microsoft.com/en-gb/azure/databricks/workflows/) for the data prep stage.
- [x] Migrate [example notebook](https://github.com/dsanmart/everywhere-reco/blob/main/examples/models/model1.ipynb) to data bricks (especially the feature engineering part).
- [x] Make research on whether we want the model running in data bricks or Azure ML Services.

**Comment by yahyalrq** [comment]
Deployed to Azure with the recommended advanced architecture
